# Default conda environment configuration for IhmStreamingVOOffline.
# To create the environment (one time):
#   conda env create -f environment.yaml
# To activate the environment (each time you open a terminal):
#   conda activate motrv2

name: motrv2
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip=23.0
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - torch==1.12.1+cu113
    - torchvision==0.13.1+cu113
    - scipy==1.7.3
    - tqdm
    - opencv-python==4.10.0.82  
    - mmcv==2.2.0
    - hydra-core==1.3.2
    - sagemaker==2.183.0
    - wandb==0.18.7
    - pycocotools==2.0.7
    - seaborn==0.12.2