# Default conda environment configuration for IhmStreamingVOOffline.
# To create the environment (one time):
#   conda env create -f environment.yaml
# To activate the environment (each time you open a terminal):
#   conda activate motrv2

name: motrv2
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pytorch=1.12.1
  - torchvision=0.9.1
  - pip=23.0
  - pip:
    - scipy==1.7.3
    - tqdm
    - opencv-python==4.10.0.82  
    - mmcv==2.2.0
    - hydra-core==1.3.2
    - sagemaker==2.183.0
    - wandb==0.18.7